### ISSUE TITLE
Ensure Netbox 4.1 compatbility

### ISSUE THREAD

**Issue by goebelmeier** [DanSheps/netbox-lifecycle#18]
### Plugin version

v1.0.4

### NetBox version

v4.1.0

### Python version

3.9

### Steps to Reproduce

1. Install Netbox 4.0.11
2. Install netbox_lifecycle 1.0.4
3. Upgrade Netbox to 4.1.0

### Expected Behavior

Update works

### Observed Behavior

Update breaks because of https://github.com/DanSheps/netbox-lifecycle/blob/38d6b09d04cec00681ea026458a3076999a566a8/netbox_lifecycle/__init__.py#L17

**Comment by DanSheps** [comment]
Completed

**Comment by jonzey0** [comment]
Not sure whether this is working after this update. 

Trying the install of the plugin on a new 4.1.0 instance of NetBox is returning the following. Running Python3.12

```
[root@netbox ~]# source /opt/netbox/venv/bin/activate
(venv) [root@netbox ~]# pip install netbox-lifecycle
Requirement already satisfied: netbox-lifecycle in /opt/netbox-4.1.0/venv/lib64/python3.12/site-packages (1.1.0)
(venv) [root@netbox ~]# cd /opt/netbox/netbox/
(venv) [root@netbox netbox]# python3 manage.py migrate
Traceback (most recent call last):
  File "/opt/netbox-4.1.0/netbox/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/netbox-4.1.0/venv/lib64/python3.12/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/opt/netbox-4.1.0/venv/lib64/python3.12/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/netbox-4.1.0/venv/lib64/python3.12/site-packages/django/core/management/base.py", line 413, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/netbox-4.1.0/venv/lib64/python3.12/site-packages/django/core/management/base.py", line 459, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox-4.1.0/venv/lib64/python3.12/site-packages/django/core/management/base.py", line 107, in wrapper
    res = handle_func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox-4.1.0/venv/lib64/python3.12/site-packages/django/core/management/commands/migrate.py", line 100, in handle
    self.check(databases=[database])
  File "/opt/netbox-4.1.0/venv/lib64/python3.12/site-packages/django/core/management/base.py", line 486, in check
    all_issues = checks.run_checks(
                 ^^^^^^^^^^^^^^^^^^
  File "/opt/netbox-4.1.0/venv/lib64/python3.12/site-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox-4.1.0/venv/lib64/python3.12/site-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox-4.1.0/venv/lib64/python3.12/site-packages/django/core/checks/urls.py", line 24, in check_resolver
    return check_method()
           ^^^^^^^^^^^^^^
  File "/opt/netbox-4.1.0/venv/lib64/python3.12/site-packages/django/urls/resolvers.py", line 519, in check
    for pattern in self.url_patterns:
                   ^^^^^^^^^^^^^^^^^
  File "/opt/netbox-4.1.0/venv/lib64/python3.12/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox-4.1.0/venv/lib64/python3.12/site-packages/django/urls/resolvers.py", line 738, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
                       ^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox-4.1.0/venv/lib64/python3.12/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox-4.1.0/venv/lib64/python3.12/site-packages/django/urls/resolvers.py", line 731, in urlconf_module
    return import_module(self.urlconf_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/netbox-4.1.0/netbox/netbox/urls.py", line 12, in <module>
    from netbox.plugins.urls import plugin_patterns, plugin_api_patterns
  File "/opt/netbox-4.1.0/netbox/netbox/plugins/urls.py", line 35, in <module>
    urlpatterns = import_string(f"{plugin_path}.api.urls.urlpatterns")
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox-4.1.0/venv/lib64/python3.12/site-packages/django/utils/module_loading.py", line 30, in import_string
    return cached_import(module_path, class_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox-4.1.0/venv/lib64/python3.12/site-packages/django/utils/module_loading.py", line 15, in cached_import
    module = import_module(module_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox-4.1.0/venv/lib64/python3.12/site-packages/netbox_lifecycle/api/urls.py", line 2, in <module>
    from .views import *
  File "/opt/netbox-4.1.0/venv/lib64/python3.12/site-packages/netbox_lifecycle/api/views/__init__.py", line 1, in <module>
    from .contract import *
  File "/opt/netbox-4.1.0/venv/lib64/python3.12/site-packages/netbox_lifecycle/api/views/contract.py", line 3, in <module>
    from netbox_lifecycle.api.serializers import VendorSerializer, SupportContractSerializer, \
  File "/opt/netbox-4.1.0/venv/lib64/python3.12/site-packages/netbox_lifecycle/api/serializers.py", line 1, in <module>
    from _serializers.contract import *
ModuleNotFoundError: No module named '_serializers'
(venv) [root@netbox netbox]# 
```

Am seeing this issue both when I included the plugin as part of the initial setup, and also tried installing the plugin after the instance was installed and running. 

Looks like the latest pull request is showing a similar issue with the automated check. https://github.com/DanSheps/netbox-lifecycle/pull/19/checks

#19
