### ISSUE TITLE
Error with NB 4.1.0 and plugin version 1.1.1 - 'tuple' object has no attribute 'items'

### ISSUE THREAD

**Issue by uck9** [DanSheps/netbox-lifecycle#21]
### Plugin version

v1.1.1

### NetBox version

v4.1.0

### Python version

3.9

### Steps to Reproduce

Install Plugin as per standard (including migration).
Access plugin pages.
Error 'tuple' object has no attribute 'items' .

### Expected Behavior

Plugin to show pages 

### Observed Behavior

```
Environment:


Request Method: GET
Request URL: https://192.168.16.101/plugins/lifecycle/license/

Django Version: 5.0.9
Python Version: 3.10.12
Installed Applications:
['django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.humanize',
 'django.forms',
 'corsheaders',
 'debug_toolbar',
 'django_filters',
 'django_htmx',
 'django_tables2',
 'django_prometheus',
 'strawberry_django',
 'mptt',
 'rest_framework',
 'social_django',
 'taggit',
 'timezone_field',
 'core',
 'account',
 'circuits',
 'dcim',
 'ipam',
 'extras',
 'tenancy',
 'users',
 'utilities',
 'virtualization',
 'vpn',
 'wireless',
 'django_rq',
 'drf_spectacular',
 'drf_spectacular_sidecar',
 'netbox_inventory.NetBoxInventoryConfig',
 'netbox_napalm_plugin.NapalmPlatformConfig',
 'netbox_lifecycle.NetBoxLifeCycle']
Installed Middleware:
['strawberry_django.middlewares.debug_toolbar.DebugToolbarMiddleware',
 'corsheaders.middleware.CorsMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'django.middleware.security.SecurityMiddleware',
 'django_htmx.middleware.HtmxMiddleware',
 'netbox.middleware.RemoteUserMiddleware',
 'netbox.middleware.CoreMiddleware',
 'netbox.middleware.MaintenanceModeMiddleware']


Template error:
In template /opt/netbox/netbox/templates/inc/filter_list.html, error at line 14
   'tuple' object has no attribute 'items'
   4 : 
   5 : <form action="." method="get">
   6 :   <div class="card">
   7 :     <div class="card-body overflow-visible d-flex flex-wrap justify-content-between py-3">
   8 :       {% for field in filter_form.hidden_fields %}
   9 :         {{ field }}
   10 :       {% endfor %}
   11 :       {# List filters by group #}
   12 :       {% for fieldset in filter_form.fieldsets %}
   13 :         <div class="col col-12">
   14 :            {% render_fieldset filter_form fieldset %} 
   15 :         </div>
   16 :       {% empty %}
   17 :         {# List all non-customfield filters as declared in the form class #}
   18 :         {% for field in filter_form.visible_fields %}
   19 :           {% if not filter_form.custom_fields or field.name not in filter_form.custom_fields %}
   20 :             <div class="col col-12">
   21 :               {% render_field field %}
   22 :             </div>
   23 :           {% endif %}
   24 :         {% endfor %}


Traceback (most recent call last):
  File "/opt/netbox-4.1.0/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/opt/netbox-4.1.0/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/netbox-4.1.0/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/netbox/netbox/netbox/views/generic/base.py", line 77, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/opt/netbox/netbox/utilities/views.py", line 125, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/opt/netbox/netbox/utilities/views.py", line 39, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/opt/netbox-4.1.0/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/opt/netbox/netbox/netbox/views/generic/bulk_views.py", line 195, in get
    return render(request, self.template_name, context)
  File "/opt/netbox-4.1.0/venv/lib/python3.10/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/opt/netbox-4.1.0/venv/lib/python3.10/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/opt/netbox-4.1.0/venv/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/opt/netbox-4.1.0/venv/lib/python3.10/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/opt/netbox-4.1.0/venv/lib/python3.10/site-packages/django/test/utils.py", line 111, in instrumented_test_render
    return self.nodelist.render(context)
  File "/opt/netbox-4.1.0/venv/lib/python3.10/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/opt/netbox-4.1.0/venv/lib/python3.10/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/opt/netbox-4.1.0/venv/lib/python3.10/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/opt/netbox-4.1.0/venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
  File "/opt/netbox-4.1.0/venv/lib/python3.10/site-packages/django/test/utils.py", line 111, in instrumented_test_render
    return self.nodelist.render(context)
  File "/opt/netbox-4.1.0/venv/lib/python3.10/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/opt/netbox-4.1.0/venv/lib/python3.10/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/opt/netbox-4.1.0/venv/lib/python3.10/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/opt/netbox-4.1.0/venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
  File "/opt/netbox-4.1.0/venv/lib/python3.10/site-packages/django/test/utils.py", line 111, in instrumented_test_render
    return self.nodelist.render(context)
  File "/opt/netbox-4.1.0/venv/lib/python3.10/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/opt/netbox-4.1.0/venv/lib/python3.10/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/opt/netbox-4.1.0/venv/lib/python3.10/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/opt/netbox-4.1.0/venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
  File "/opt/netbox-4.1.0/venv/lib/python3.10/site-packages/django/test/utils.py", line 111, in instrumented_test_render
    return self.nodelist.render(context)
  File "/opt/netbox-4.1.0/venv/lib/python3.10/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/opt/netbox-4.1.0/venv/lib/python3.10/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/opt/netbox-4.1.0/venv/lib/python3.10/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/opt/netbox-4.1.0/venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/opt/netbox-4.1.0/venv/lib/python3.10/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/opt/netbox-4.1.0/venv/lib/python3.10/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/opt/netbox-4.1.0/venv/lib/python3.10/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/opt/netbox-4.1.0/venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/opt/netbox-4.1.0/venv/lib/python3.10/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/opt/netbox-4.1.0/venv/lib/python3.10/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/opt/netbox-4.1.0/venv/lib/python3.10/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/opt/netbox-4.1.0/venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/opt/netbox-4.1.0/venv/lib/python3.10/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/opt/netbox-4.1.0/venv/lib/python3.10/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/opt/netbox-4.1.0/venv/lib/python3.10/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/opt/netbox-4.1.0/venv/lib/python3.10/site-packages/django/template/defaulttags.py", line 326, in render
    return nodelist.render(context)
  File "/opt/netbox-4.1.0/venv/lib/python3.10/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/opt/netbox-4.1.0/venv/lib/python3.10/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/opt/netbox-4.1.0/venv/lib/python3.10/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/opt/netbox-4.1.0/venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 210, in render
    return template.render(context)
  File "/opt/netbox-4.1.0/venv/lib/python3.10/site-packages/django/template/base.py", line 173, in render
    return self._render(context)
  File "/opt/netbox-4.1.0/venv/lib/python3.10/site-packages/django/test/utils.py", line 111, in instrumented_test_render
    return self.nodelist.render(context)
  File "/opt/netbox-4.1.0/venv/lib/python3.10/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/opt/netbox-4.1.0/venv/lib/python3.10/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/opt/netbox-4.1.0/venv/lib/python3.10/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/opt/netbox-4.1.0/venv/lib/python3.10/site-packages/django/template/defaulttags.py", line 242, in render
    nodelist.append(node.render_annotated(context))
  File "/opt/netbox-4.1.0/venv/lib/python3.10/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/opt/netbox-4.1.0/venv/lib/python3.10/site-packages/django/template/library.py", line 258, in render
    _dict = self.func(*resolved_args, **resolved_kwargs)
  File "/opt/netbox/netbox/utilities/templatetags/form_helpers.py", line 58, in render_fieldset
    for item in fieldset.items:

Exception Type: AttributeError at /plugins/lifecycle/license/
Exception Value: 'tuple' object has no attribute 'items'
```

**Comment by uck9** [comment]
to follow up - I had lifecycle 1.0.4 running with NB 4.0.9 successfully.  The upgrade to 4.1.0 and associated upgrade of lifecycle to 1.1.1 triggered the issue.  I've attempted a couple of rebuilds now with the same issue.

**Comment by uck9** [comment]
Just run the new version up in lab and all looking good.  Really appreciate the damn quick response on that one :)

**Comment by DanSheps** [comment]
Yeah, sorry about that.  Will get the tests fixed and it hopefully won't happen again.  ;)

**Comment by jonzey0** [comment]
Yup. Just successfully installed this new version on my instance as well. Thanks mate!
